### ISSUE TITLE
Feature request: Member + Post Management by yaml

### ISSUE THREAD

**Issue by JustKode** [Dcom-KHU/dcom-landing-page#15]
## 🚀 Feature Request
yaml 파일을 이용해서, 페이지 렌더링이 가능한데요,
이를 바탕으로, 회원 목록, Post 작성 목록을 쉽게 수정 할 수 있습니다.
코드를 깔 필요도 없이, Github 자체 내장 코드 수정 기능을 통해서 바로바로 회원 목록, Post 목록을 수정 하는 게 사용성이 좋아 보이네요.

yaml 이 수정 될 때, Github Action이 Trigger 되게 하면 더 좋을 것 같아요.

## 📎 Additional context
https://www.gatsbyjs.com/docs/how-to/sourcing-data/sourcing-from-json-or-yaml/

**Comment by FacerAin** [comment]
@all-contributors please add @JustKode for infra

**Comment by FacerAin** [comment]
좋은 의견 감사합니당!!
코드 단의 변경 없이 컨텐츠를 수정하고 추가할 수 있게 하는 것이 참 중요한 부분 같아요!
말씀하신대로 야믈 파일 등을 통해서 블로그 사용성을 높일 수 있도록 진행해볼게요!
감사합니닷  🚀🚀

**Comment by JustKode** [comment]
이미 JSON으로 관리 예정 중으로 보이기 때문에 Issue 종료 하겠습니다.
나중에 Member 명부 관리도 이를 통해서 이뤄 지면 좋을 것 같아요.
